
import { Inter } from 'next/font/google';
import './globals.css';
import Header from '../app/components/header';
import Footer from '../app/components/footer';
import { Providers } from './providers';  // Import the Providers component

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Wrap the children with Providers for React Query setup */}
        {/* <Providers> */}
          {/* Navbar included for all pages */}
          <Header />

          {/* Main content is injected here */}
          <main className="min-h-screen flex flex-col">
            {children}
          </main>
          <Footer />
        {/* </Providers> */}
        
      </body>
    </html>
  );
}

// import { Inter } from 'next/font/google';
// import './globals.css';
// import Header from '../app/components/header';
// import { Providers } from './providers';  // Now, this should work

// const inter = Inter({ subsets: ['latin'] });

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         {/* Wrap the children with Providers for React Query setup */}
//         <Providers>
//           {/* Navbar included for all pages */}
//           <Header />

//           {/* Main content is injected here */}
//           <main className="min-h-screen flex flex-col">
//             {children}
//           </main>
//         </Providers>
//       </body>
//     </html>
//   );
// }
